### PR TITLE
add music

### PR DESCRIPTION
**Pull request by geekingreen**

### CODE REVIEW

**Comment by ignacioxd** [comment]
OMG! I'm super excited to try this out!

I'm going to host this as a beta version to share it with the group before merging.

**Comment by ignacioxd** [comment]
I'm getting this error: 

> The AudioContext was not allowed to start. It must be resume (or created) after a user gesture on the page. https://goo.gl/7K7WLu`

did you see this on your end? Check the console at [https://raginmages.net/](https://raginmages.net/)

**Comment by geekingreen** [comment]
Hmmm, I'm not getting that error... Chrome 66

**Comment by ignacioxd** [comment]
Is audio working for you?

**Comment by geekingreen** [comment]
yeah no problems here

**Comment by geekingreen** [comment]
I did finally get that to show up in the console, but the music still plays just fine either way.

**Comment by ignacioxd** [comment]
I got it working. Amazing work!!

**Pull request merged**
